name: PBI Repo Checks

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run checks
        run: |
          python tools/require_files.py
          python tools/lint_dax.py
          python tools/check_rules.py
          python tools/check_changelog_on_pr.py
